### ISSUE TITLE
Can't Enter Integer, Although Input Is Correct

### ISSUE THREAD

**Issue by edluong** [edluong/fivedraw#6]
```
Your Hand:
1: (2, 'Clubs')
2: (4, 'Clubs')
3: (5, 'Spades')
4: ('Queen', 'Hearts')
5: ('Ace', 'Hearts')
You have: high card
Stack Size: 200


CPU Hand:
1: (3, 'Clubs')
2: (8, 'Clubs')
3: (9, 'Spades')
4: ('Jack', 'Diamonds')
5: ('King', 'Clubs')
CPU has: high card
Stack Size: 200
Which cards to discard? (Type the number, e.g.: 1 2 3) or k to keep: 4  
Integer was not entered in!
Which cards to discard? (Type the number, e.g.: 1 2 3) or k to keep: 4
Traceback (most recent call last):
  File "app.py", line 11, in <module>
    game.discard_choice()
  File "/home/edge/dev/fivedraw/game.py", line 97, in discard_choice
    self.player.get_hand().discard(_indexes)
  File "/home/edge/dev/fivedraw/hand.py", line 48, in discard
    self.hand.remove(_card)
ValueError: list.remove(x): x not in list
Makefile:6: recipe for target 'run' failed
make: *** [run] Error 1
```

**Comment by edluong** [comment]
havent seen this in a while

**Comment by edluong** [comment]
related to #14
